### List all users
GET https://localhost:7052/auth/list/users

### Get auth token 
POST https://localhost:7052/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=james@test.com&password=test

### Get random recipe
GET https://localhost:7052/api/Recipes/random
Authorization: Bearer 


### Send bad POST request
POST https://localhost:7052/api/Recipes
Authorization: Bearer 
Content-Type: application/json

{}

### Add new recipe
POST https://localhost:7052/api/Recipes
Authorization: Bearer 
Content-Type: application/json

{
  "name": "oops",
  "description": "oops",
  "lookupCode": "oops",
  "tags": ["oops"],
  "ingredients": [
    {
      "name": "oops",
      "quantity" : 1,
      "unit": "oops"
    }
  ]
}

### Get recipe by lookup code
GET https://localhost:7052/api/Recipes/oops
Authorization: Bearer 